/*#ifndef PARABOLA_PLATFORMINTERFACE_IOS_H
#define PARABOLA_PLATFORMINTERFACE_IOS_H

//#include "Platform.h"

PARABOLA_NAMESPACE_BEGIN

class PARABOLA_API iOSInterface{
public:

};

PARABOLA_NAMESPACE_END
#endif // PARABOLA_PLATFORMINTERFACE_IOS_H*/
